### ISSUE TITLE
finding rST through rMLST scheme

### ISSUE THREAD

**Issue by kaehwan** [jordanlab/STing#12]
hi @ar0ch, I appreciate your work very much. I have successfully built a rMLST database using STing indexer.
However, the Status values are always no_st_in_table due to mismatch(es) in one or several locus. May I know if there is a way to find the closest rST or the species identity using STing? Thank you very much.

**Comment by ar0ch** [comment]
Hi @kaehwan, unfortunately STing can only report exact matches.  However, it is relatively straight forward to find the closest ST given the output alleles and the database ST table (at least in a somewhat naïve way).  Compare each allele in your output to the reference panel and any mismatches are scored 1 and matches scored 0.  The sum for each reference comparison is your distance (i.e. 2 mismatches = distance of 2).  You can choose to treat missing/no calls as pairwise deletions or not (might be useful to try both ways).    This can be accomplished pretty easily in base R; a very, *very* simple example below.  Reference 3 is the closest, and has only one mismatch, followed by ref 4.

``` r
your_results = data.frame(
    a = 1,
    b = 4,
    c = 4, 
    row.names = "your_sample"
)

your_results
#>             a b c
#> your_sample 1 4 4

reference_table = data.frame(
    a = c(45, 98, 1, 70),
    b = c(5, 23, 512, 123),
    c = c(1, 3, 4, 4),
    row.names = c("ref1", "ref2", "ref3", "ref4")
)

reference_table
#>       a   b c
#> ref1 45   5 1
#> ref2 98  23 3
#> ref3  1 512 4
#> ref4 70 123 4
distance = do.call(rbind.data.frame, apply(reference_table, 1, function(x) x - your_results))

distance
#>       a   b  c
#> ref1 44   1 -3
#> ref2 97  19 -1
#> ref3  0 508  0
#> ref4 69 119  0

distance[distance != 0] = 1

distance
#>      a b c
#> ref1 1 1 1
#> ref2 1 1 1
#> ref3 0 1 0
#> ref4 1 1 0

distance = sort(apply(distance, 1, sum))

distance
#> ref3 ref4 ref1 ref2 
#>    1    2    3    3
```

<sup>Created on 2021-12-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kaehwan** [comment]
Hi @ar0ch, thank you so much for your guidance. Your R script works perfectly to identify the closest rST or species id. I will close the issue then.
