### ISSUE TITLE
Proper usage of index

### ISSUE THREAD

**Issue by MatteoSchiavinato** [jordanlab/STing#6]
Hi, 

I'm new to this software, and I have been trying to make it work for the past two days. 
I'm using the *vfdb* database provided by you.

This is my STing command:
```
OUTDIR="/path/to/output_directory"
DATABASE="/path/to/STing_datasets-20200718/vfdb/db/gene_set"
READ_BASE="/path/to/fastq/reads"
PREFIX="F3_F_R1"

./programs/STing/typer \
--index-prefix ${DATABASE} \
--fastq-1-files ${READ_BASE}/${PREFIX}.fastq \
--sample-name ${PREFIX} \
--sensitive \
--kmer-length 30 \
--n-top-alleles 2 \
--output-file ${OUTDIR}/${PREFIX}.out \
--print-tidy
```

I am a bit confused on how to use the `--index-prefix` option. From what I could get, it should point at the database and there should be a prefix word for all files in such database that should be included as a basename (sort of like the bowtie2-build basename structure). 

In this case it is the one I specify in `DATABASE`, but I get this error:
```
ERROR: Could not open the input file '/path/to/STing_datasets-20200718/vfdb/db/gene_set.prof_idx.sa'
ERROR: Index file '/path/to/STing_datasets-20200718/vfdb/db/gene_set.prof_idx.sa' not found.
```
I "masked" the paths leaving only the relevant parts in. The paths are correct, i.e. that's my index prefix and all of the other files exist, except for this one.

**Comment by MatteoSchiavinato** [comment]
Thanks! That explains the issue. 

Maybe another thing that could be clearer is whether I can declare `--sample-name item1,item2,...,itemN` the same way I would do with `--fastq-1-files file1,file2,…,fileN`. I did it like that for now and it did not complain but I never got to see an output due to this issue with the index.

**Comment by ar0ch** [comment]
In both applications,  `--fastq-1-files` and `--fastq-2-files` are accumulators, so they can be given multiple times or a list of files can be given.  The ordering of inputs is preserved and they're assumed to be paired between `1 <> 2`.  However, both applications only operate on one sample at a time -- _do not_ provide reads from multiple samples in one run.  The classification problem, as solved by `STing`, is embarrassingly parallel and parallelism is achieved through additional instances.

**Comment by MatteoSchiavinato** [comment]
Roger that. Thanks!
