### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by yasirniazi** [jordanlab/STing#9]
No file found in the following link kindly provides files.

wget https://github.com/jordanlab/STing/releases/download/1.0.0/sting_v1.0.0.tar.gz

404 not found error occurred 

See  below for error

yasirniazi@yasirniazi:~/STing-master$ wget https://github.com/jordanlab/STing/releases/download/1.0.0/sting_v1.0.0.tar.gz
--2020-10-29 19:46:51--  https://github.com/jordanlab/STing/releases/download/1.0.0/sting_v1.0.0.tar.gz
Resolving github.com (github.com)... 13.234.176.102
Connecting to github.com (github.com)|13.234.176.102|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-29 19:46:53 ERROR 404: Not Found.

**Comment by ar0ch** [comment]
Please see the releases section for the most update to date release: https://github.com/jordanlab/STing/releases


There's a small typo in the readme for the url

**Comment by yasirniazi** [comment]
Thank you. Problem Solved
